spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tasklist
    username: postgres
    password: 1122
  sql:
    init:
      mode: always
      continue-on-error: false
#      data-locations: classpath:demo_data.sql
security:
  jwt:
    secret: dFdUM1RZUlVISlJINDc0S0lMS1NXU1ZWQkJERkRHMTIzMz09LS0=
    access: 1
    refresh: 30